version: '3'
services:

 medikove:
  build:
   dockerfile: Dockerfile.dev
   context: ../medikove
  stdin_open: true
  ports:
   - "3000:3000"
  volumes:
   - /app/node_modules
   - ./medikove:/app

 redis:
  image: 'redis:latest'
 
 nginx:
  depends_on:
    - medikove
  restart: always
  build:
   dockerfile: Dockerfile.dev
   context: ./nginx
  ports:
   - '3050:80'
  
 

   