version: '3'
services:

 medikove:
  build:
   dockerfile: Dockerfile.dev
   context: .
  stdin_open: true
  ports:
   - "3000:3000"
  volumes:
   - /app/node_modules
   - .:/app

 backend:
  build:
   dockerfile: Dockerfile.dev
   context: ./medikove-backend
  ports:
   - "8083:8083"
  environment:
   - REDIS_HOST=redis
   - REDIS_PORT=6379
  depends_on:
   - redis

 redis:
  image: 'redis/redis-stack'
  ports:
   - '6379:6379'
   - '8001:8001'
  
 nginx:
  depends_on:
    - medikove
  restart: always
  build:
   dockerfile: Dockerfile.dev
   context: ./nginx
  ports:
   - '3050:80'
  
 

   